spring:
  # DataSource������
  datasource:
    username: root
    password: hailian2020
    url: jdbc:mysql://localhost:3306/mybatis?serverTimezone=Asia/Shanghai&useUnicode=true&characterEncoding=utf-8&allowMultiQueries=true
    driver-class-name: com.mysql.cj.jdbc.Driver
    type: com.alibaba.druid.pool.DruidDataSource

    #Spring Boot Ĭ���ǲ�ע����Щ����ֵ�ģ���Ҫ�Լ���
    #druid ����Դר������
    initialSize: 5
    minIdle: 5
    maxActive: 20
    maxWait: 60000
    timeBetweenEvictionRunsMillis: 60000
    minEvictableIdleTimeMillis: 300000
    validationQuery: SELECT 1 FROM DUAL
    testWhileIdle: true
    testOnBorrow: false
    testOnReturn: false
    poolPreparedStatements: true

    #���ü��ͳ�����ص�filters��stat:���ͳ�ơ�log4j����־��¼��wall������sqlע��
    #�������ʱ����  java.lang.ClassNotFoundException: org.apache.log4j.Priority
    #���� log4j �������ɣ�Maven ��ַ��https://mvnrepository.com/artifact/log4j/log4j
    filters: stat,wall,log4j
    maxPoolPreparedStatementPerConnectionSize: 20
    useGlobalDataSourceStat: true
    connectionProperties: druid.stat.mergeSql=true;druid.stat.slowSqlMillis=500


# ����mybatis
mybatis:
  type-aliases-package: edu.scut.pojo # �Զ������ñ���������ȡΪ�����ı���������edu.scut.pojo.User ����ΪUser
  mapper-locations: classpath:mybatis/mapper/*.xml # ��classpath:mybatis/mapperĿ¼�µ�����xmlɨ�貢����
